version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nest-typeorm
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
